### ISSUE TITLE
大佬，第三步如果选择定时。不管输入多少时间都会闪退

### ISSUE THREAD

**Issue by nagashirosan** [Koileo/ticket_for_allcpp#2]
第三步如果选择定时。不管输入多少时间都会闪退。会瞬间提示“时间已经过去了主人”后结束运行。然后如果选择捡漏的话，就算是有票的链接，不会提示你选择哪一天的票。就会直接开枪也不知道抢那一个，但是不会生成订单会一直提醒操作频繁

**Comment by Koileo** [comment]
请检查你填的时间戳默认是毫秒制的 13位数字

**Comment by Koileo** [comment]
你选择的票是在cookie.txt提前写好的，可以看f12 打开购票页面选择你的活动，里面有一个响应，包含了所有票的ticketid，在第二行填入你的ticketid

**Comment by Koileo** [comment]
操作频繁尝试降低线程数，和间隔时间，建议是3线程，间隔时间1s

**Comment by Koileo** [comment]
https://t.me/+qmRJ_jp6IEcyYzQ1
可以进群
