### ISSUE TITLE
未开票时抢票导致程序异常退出

### ISSUE THREAD

**Issue by Lilv712** [Koileo/ticket_for_allcpp#6]
在process_thread函数中加入try except已初步解决

**Comment by Koileo** [comment]
可以发一下你改后的代码吗，高三生没时间，我这边改一下

**Comment by Lilv712** [comment]
> 可以发一下你改后的代码吗，高三生没时间，我这边改一下

只是在process thread函数里加了个tryexcept(

    try:
        cookies = cookie_string_to_dict(cookie_str)

        pur = requests.get(
            url='https://www.allcpp.cn/allcpp/user/purchaser/getList.do',
            cookies=cookies,
            headers=headers,
        )

        purrer = pur.content.decode("utf-8")
        purrer_data = json.loads(purrer)
        print(purrer_data)
        ids = [str(item["id"]) for item in purrer_data]
        ids_str = ",".join(ids)
        id_count = len(ids)
        print(f"IDs for ticket {ticketid}: {ids_str}")
        json_data = {}


        retn_params = sign_for_post(ticketid)
        url = 'https://www.allcpp.cn/allcpp/ticket/buyTicketAliWapPay.do?ticketTypeId=' + str(ticketid) + '&count=' + str(
                id_count) + '&' + retn_params + '&purchaserIds=' + ids_str
        print(url)
        response = requests.post(
                url=url,
                cookies=cookies,
                headers=headers,
                json=json_data,
        )
        resp = response.content.decode("utf-8")
        parsed_resp = json.loads(resp)
        print(parsed_resp)
    except:
        pass

**Comment by Lilv712** [comment]
这个加法是有问题的，会导致不进后面的else，从而脚本运行过快
