### ISSUE TITLE
打开闪退

### ISSUE THREAD

**Issue by yyx119** [Koileo/ticket_for_allcpp#9]
为什么下载打开这个后会闪退哇
![微信图片_20240929184831](https://github.com/user-attachments/assets/88ff1ed0-e462-4434-9e9a-6314b98bdea0)

**Comment by wlwxj** [comment]
+1

**Comment by Mother-Ship** [comment]
应该是不存在那两个txt文件，从repo里下下来放在exe同目录试试，或者直接用python启动repo里的脚本

**Comment by Mother-Ship** [comment]
> +1

应该是不存在那两个txt文件，从repo里下下来放在exe同目录试试，或者直接用python启动repo里的脚本

**Comment by Koileo** [comment]
没有填写cookie值
